apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftapp
  labels:
    app: giftapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giftapp
  template:
    metadata:
      labels:
        app: giftapp
    spec:
      imagePullSecrets:
      - name: icr
      containers:
      - name: giftapp-container
        image: us.icr.io/sn-labs-u31241596/giftapp:latest
        ports:
        - containerPort: 3060
        env:
        - name: MONGO_URL
          value: mongodb://root:GInG5giBHeqZ5NsFuF5WhDY5@mongodb-service:27017
        - name: JWT_SECRET
          value: setasecret
        - name: DATASRC
          value: gifts.json
---
apiVersion: v1
kind: Service
metadata:
  name: gift-app-service
spec:
  type: NodePort
  selector:
    app: giftapp
  ports:
  - port: 80
    targetPort: 3060
    protocol: TCP
